theme: jekyll-theme-slate
url: https://storeyclubwebsite.github.io/storeyclubwebsite
lang: "nl-NL"
facebook_url: "https://www.facebook.com/Storeyclub"

paginate: 4
paginate_path: "/posts/post:num/"

collections:
  albums:
    output: true

defaults:
- scope:
    path: "pictures"
  values:
    image: true
